apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: machine-node-linker
  annotations:
    # This Annotation sets a toleration on all resources created in the namespace.  If you are going to use this controller to add nodes,
    #  the catalog, bundle export, and controller must be allowed to run on controlplane nodes as they will be the only nodes available at bootstrap
    scheduler.alpha.kubernetes.io/defaultTolerations:
      '[{"operator": "Exists", "effect":
      "NoSchedule", "key": "node-role.kubernetes.io/master"}]'
  name: machine-node-linker
spec:
  finalizers:
    - kubernetes
